POST http://localhost:3000/test
Content-Type: application/json

{
    "testId": "00001",
    "comment": "고경준은 xxx입니다lsdkflskflksd",
    "title": "고경준천재",
    "pwd": "1114"
}

###

POST http://dist03-env.eba-tp9w8wyv.ap-northeast-2.elasticbeanstalk.com/test
Content-Type: application/json

{
    "testId": "00002",
    "comment": "Gpex 토큰좀 주세요~~~~",
    "title": "고경준천재",
    "pwd": "1114"
}

###
