###

GET http://localhost:3000/board
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJJZCI6ImxhbmNlNzciLCJtZW1iZXJOYW1lIjoi6rOg6rK97KSAIiwiaWF0IjoxNjc4MDQzNjA1LCJleHAiOjE2NzgxMzAwMDV9.NgpBKf5UhcMzOzMJtjB-PclGOSbWtwfPcevPk29A1SA

###


POST http://localhost:3000/board
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJJZCI6ImxhbmNlNzciLCJtZW1iZXJOYW1lIjoi6rOg6rK97KSAIiwiaWF0IjoxNjczNjUxOTc3LCJleHAiOjE2NzM3MzgzNzd9.QNuyLPJeuAxIjAhOUxRCFSc9EPZf2xZ7b9r1HMI0B-s

{
    "name": "고경준천재님ㄴㅇlfsdkfldks",
    "contents": "dsflkgsdflkglsdfglsdk",
    "title": "dsflkgsdflkglsdfglsdk",
    "createDate": "dsflkgsdflkglsdfglsdk",
    "pwd": "dsflkgsdflkglsdfglsdk"
}



###

POST http://localhost:3000/login
Content-Type: application/json

{
    "id" : "lance77",
    "password" : "ka1114"

}

###
